# Generated by Django 5.0.1 on 2026-05-07 14:36

from django.conf import settings
from django.db import migrations, models
import re


def normalize_phone_number(value):
    if not value:
        return ""
    digits = re.sub(r"\D+", "", value)
    if digits.startswith("00"):
        digits = digits[2:]
    return digits


def populate_phone_normalized(apps, schema_editor):
    Broker = apps.get_model("brokers", "Broker")
    for broker in Broker.objects.all().only("pk", "phone_number"):
        broker.phone_normalized = normalize_phone_number(broker.phone_number)
        broker.save(update_fields=["phone_normalized"])


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_broker_broker_tenant_status_idx_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="phone_normalized",
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.RunPython(populate_phone_normalized, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(
                fields=["tenant", "phone_normalized"], name="broker_tenant_phonekey_idx"
            ),
        ),
    ]
