# Generated by Django 5.0.1 on 2026-05-07 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_broker_broker_tenant_status_idx_and_more"),
        ("customers", "0002_customer_customer_tenant_status_idx_and_more"),
        ("latra", "0001_initial"),
        ("tenants", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "status"], name="latra_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "expiry_date"], name="latra_tenant_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "status", "expiry_date"],
                name="latra_tenant_stat_exp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "vehicle"], name="latra_tenant_vehicle_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "customer"], name="latra_tenant_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "broker"], name="latra_tenant_broker_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latrarecord",
            index=models.Index(
                fields=["tenant", "service_name"], name="latra_tenant_service_idx"
            ),
        ),
    ]
