# Generated by Django 5.0.1 on 2026-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="uservehiclepermission",
            index=models.Index(
                fields=["tenant", "user"], name="userperm_tenant_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uservehiclepermission",
            index=models.Index(
                fields=["tenant", "vehicle_category"], name="userperm_tenant_cat_idx"
            ),
        ),
    ]
