# Generated by Django 5.0.1 on 2026-05-07 14:36

from django.conf import settings
from django.db import migrations, models
import re


def normalize_phone_number(value):
    if not value:
        return ""
    digits = re.sub(r"\D+", "", value)
    if digits.startswith("00"):
        digits = digits[2:]
    return digits


def populate_phone_normalized(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    for customer in Customer.objects.all().only("pk", "phone_number"):
        customer.phone_normalized = normalize_phone_number(customer.phone_number)
        customer.save(update_fields=["phone_normalized"])


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0003_broker_phone_normalized_and_more"),
        ("customers", "0002_customer_customer_tenant_status_idx_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_normalized",
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.RunPython(populate_phone_normalized, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "phone_normalized"],
                name="customer_tenant_phonekey_idx",
            ),
        ),
    ]
