# Generated by Django 5.0.1 on 2026-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
