# Generated by Django 5.0.1 on 2026-05-07 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_customer_tenant_status_idx_and_more"),
        ("tenants", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["tenant", "status"], name="vehicle_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["tenant", "vehicle_category"], name="vehicle_tenant_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["tenant", "plate_number"], name="vehicle_tenant_plate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["tenant", "customer"], name="vehicle_tenant_customer_idx"
            ),
        ),
    ]
